### ISSUE TITLE
Chrome cookie warning

### ISSUE THREAD

**Issue by red-sight** [wialon/wialonjs-api#2]
Chrome dev tools returns a new warning message in console when using this library:

> A cookie associated with a cross-site resource at http://hst-api.wialon.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by ashmigelski** [comment]
Hello

Library do not set any cookie, so issue is not on it side. We'll initiate fix on wialon side.

Thanks for reporting!
